{% set version = "0.4.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sfheaders
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sfheaders_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sfheaders/sfheaders_{{ version }}.tar.gz
  sha256: f939c9278e483a957347c48de954669285e51bd54fe17a92ce0e92e74928bdf3

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-geometries               # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0.10
    - r-geometries >=0.2.2
  run:
    - r-base
    - r-rcpp >=1.0.10
    - r-geometries >=0.2.2

test:
  commands:
    - $R -e "library('sfheaders')"           # [not win]
    - "\"%R%\" -e \"library('sfheaders')\""  # [win]

about:
  home: https://dcooley.github.io/sfheaders/
  license: MIT
  summary: Converts between R and Simple Feature 'sf' objects, without depending on the Simple Feature library. Conversion functions are available at both the R level, and through 'Rcpp'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
